### ISSUE TITLE
Inspecting the WebView no longer works

### ISSUE THREAD

**Issue by rodi01** [skpm/sketch-module-web-view#71]
I'm running Sketch-module-web-view@2.1.0. I've already ran `defaults write com.bohemiancoding.sketch3 WebKitDeveloperExtras -bool true` only the reload options shows up.

**Comment by robintindale** [comment]
I think its now controlled by `  browserWindow._webview.configuration().preferences().setValue_forKey_(true,"developerExtrasEnabled");
  `

Maybe we can add an `allowInspectElement` option or something, which is default `false`

**Comment by mathieudutour** [comment]
Ah indeed, I didn't realised it was different for a WKWebview. I'll add a `webPreferences.devTools` option to match the Electron API

**Comment by mathieudutour** [comment]
fixed in 2.1.1

**Comment by parkerhendo** [comment]
Still having issues with this. I could be doing it wrong as I'm new to plugin development, so would love some guidance.
Here is my options object
 ```
const options = {
        identifier: 'window',
        width: 1000,
        height: 800,
        show: false,
        alwaysOnTop: true,
        movable: false,
        minimizable: false,
        webPreferences: {
            devTools: true,
        },
    };
```
then I call `openDevTools()` here
```
webContents.on('did-finish-load', () => {
        webContents.opeDevTools();
        UI.message('UI loaded!');
})
```

Thanks in advance for any help.

**Comment by mathieudutour** [comment]
`openDevTools` isn't implemented, but you should be able to right click and inspect

**Comment by parkerhendo** [comment]
> `openDevTools` isn't implemented, but you should be able to right click and inspect

That was my first thought, but not having any luck with that either.

**Comment by mathieudutour** [comment]
Hum weird, what version of the package are you using? I'll have a look

**Comment by parkerhendo** [comment]
> Hum weird, what version of the package are you using? I'll have a look

using version `2.1.5`.

**Comment by mathieudutour** [comment]
Could you try with version 3.0?

**Comment by parkerhendo** [comment]
> Could you try with version 3.0?

Still no luck. I'm using React within the web view, but have also tried regular HTML but the result was the same.

**Comment by mathieudutour** [comment]
Wait when you mean "right click doesn't work", it is because the contextual menu isn't working? If so it's probably because you are blocking the right click. That's the default if you use the `with-webview` template: https://github.com/skpm/with-webview/blob/master/template/resources/webview.js#L1-L4

**Comment by parkerhendo** [comment]
> Wait when you say "right click doesn't work", it is because the contextual menu isn't working? If so it's probably because you are blocking the right click. That's the default if you use the `with-webview` template: https://github.com/skpm/with-webview/blob/master/template/resources/webview.js#L1-L4

Ah, yes that was this issue. Didn't know it was disabled by default and hadn't thought to look in `webview.js`.

Thanks for clarifying!
