### ISSUE TITLE
JSContext can not destroy

### ISSUE THREAD

**Issue by ronghui1219** [skpm/sketch-module-web-view#76]
after open close many times DevTools Sketch Plugin，there are many JSContext and webview Instance has been created，i create a plugin use sketch-module-web-view too， can i destroy JSContext and webview Instance when i click close window？
<img width="379" alt="2018-11-30 3 57 18" src="https://user-images.githubusercontent.com/1631704/49276308-1304aa00-f4b9-11e8-8a15-d82871749f58.png">

**Comment by mathieudutour** [comment]
should be fixed in the latest version

**Comment by yvanwangl** [comment]
This issue is not fixed?  sketch-module-web-view version is 3.4.1;
